### ISSUE TITLE
Error on Heartbeat

### ISSUE THREAD

**Issue by surewhynotmon** [BoBeR182/PoGoBoWo#25]
Is the error below due to Directions API setup?
I have tested my API key with `https://maps.googleapis.com/maps/api/directions/json?origin=75+9th+Ave+New+York,+NY&destination=MetLife+Stadium+1+MetLife+Stadium+Dr+East+Rutherford,+NJ+07073&departure_time=1541202457&traffic_model=best_guess&key=MY_API_KEY` and it seems to work. Anything that might cause this?

````
2016-07-28 18:19:18,423 [    pgoapi] [ INFO] Login process completed
2016-07-28 18:19:48,528 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
2016-07-28 18:19:48,530 [   pokebot] [ERROR] Main loop has an ERROR, restarting 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "pokebot.py", line 95, in main
    api.main_loop()
  File "/home/vagrant/dev/PoGoBoWo/pgoapi/pgoapi.py", line 564, in main_loop
    self.heartbeat()
  File "/home/vagrant/dev/PoGoBoWo/pgoapi/pgoapi.py", line 240, in heartbeat
    if res.get("direction", -1) == 102:
````

**Comment by surewhynotmon** [comment]
More output about the rpc error
````
2016-07-28 18:35:05,632 [   rpc_api] [DEBUG] Execution of RPC
2016-07-28 18:35:05,634 [connectionpool] [ INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-28 18:35:35,726 [connectionpool] [DEBUG] "POST /plfe/504/rpc HTTP/1.1" 502 332
2016-07-28 18:35:35,727 [   rpc_api] [DEBUG] Parsing main RPC response...
2016-07-28 18:35:35,727 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
2016-07-28 18:35:35,728 [   rpc_api] [DEBUG] HTTP output:

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
````

**Comment by BoBeR182** [comment]
Sounds like its on googles end, I will close this unless it continues.

**Comment by ridetheflatline** [comment]
I'm experiencing similar (if not same problem)

[errlog.txt](https://github.com/BoBeR182/PoGoBoWo/files/389467/errlog.txt)

**Comment by BoBeR182** [comment]
@ridetheflatline You have two things going on.
One is a bug the first error, because you have not placed any eggs in an incubator.
Second the servers are down and giving you a 502 response.

Please open a new bug for issue number 1.
