### ISSUE TITLE
No eggs in incubator - [ERROR] Main loop has an ERROR, restarting 'target_km_walked'

### ISSUE THREAD

**Issue by ridetheflatline** [BoBeR182/PoGoBoWo#32]
Error occurs if no eggs have been placed in an incubator.

2016-07-29 07:07:35,040 [   pokebot] [ERROR] Main loop has an ERROR, restarting 'target_km_walked'
Traceback (most recent call last):
  File "pokebot.py", line 95, in main
    api.main_loop()
  File "C:\Python27\PoGoBoWo\pgoapi\pgoapi.py", line 573, in main_loop
    self.spin_near_fort()  # check local pokestop
  File "C:\Python27\PoGoBoWo\pgoapi\pgoapi.py", line 298, in spin_near_fort
    self.walk_to((fort['latitude'], fort['longitude']))
  File "C:\Python27\PoGoBoWo\pgoapi\pgoapi.py", line 277, in walk_to
    self.heartbeat()
  File "C:\Python27\PoGoBoWo\pgoapi\pgoapi.py", line 265, in heartbeat
    self.log.info("List of Pokemon:\n" + get_inventory_data(res, self.pokemon_names) + "\nTotal Pokemon count: " + str(get_pokemon_num(res)) + "\nEgg Hatching status: " + get_incubators_stat(res))
  File "C:\Python27\PoGoBoWo\pgoapi\poke_utils.py", line 43, in get_incubators_stat
    x['egg_incubator']['start_km_walked']), inventory_items_incubator_list)))
  File "C:\Python27\PoGoBoWo\pgoapi\poke_utils.py", line 42, in <lambda>
    x['egg_incubator']['target_km_walked'],
KeyError: 'target_km_walked'

[errlog.txt](https://github.com/BoBeR182/PoGoBoWo/files/389587/errlog.txt)

**Comment by BoBeR182** [comment]
Fixed in bb422cb052bb3e8bd9e0caf8d1835c85fed75b09
