### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by buriedsand** [BoBeR182/PoGoBoWo#33]
Hi there! This is my first time running the program, so I enter this into terminal:
Brandons-MBP:PoGoBoWo brandon$ `python pokebot.py -i 0--cache`
And it spits out this exception:
```
Traceback (most recent call last):
  File "pokebot.py", line 105, in <module>
    main()
  File "pokebot.py", line 74, in main
    config = init_config()
  File "pokebot.py", line 43, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
I'm sorry I'm not sure what I'm doing wrong. Thanks in advance!

**Comment by BoBeR182** [comment]
Servers might be down, or you configured your config.json incorrectly. May you attach it here without your username, password, or API key.

**Comment by buriedsand** [comment]
Yes, sorry for the delayed response.
Just realized my quotations were off. Some of mine were curved when they should all be straight. (That's the best I can explain it). For others with my problem, see if your quotation marks look different. They should be straight! I'm not sure if I typed the quotation marks myself or if somehow they changed, but that seemed to be the problem.
Everything seems to be working now. Also, had to add a space between the `0` and `--cache` but that wasn't so hard to figure out. :)
