### ISSUE TITLE
keyError: target_km_walked

### ISSUE THREAD

**Issue by lennon681** [BoBeR182/PoGoBoWo#54]
I'm new to Python but was able to get the environment all setup and running.  The bot starts up and logs in fine but shortly after trying to walk to the first pokestop I get an error:

2016-08-03 00:20:36,632 [   pokebot] [ERROR] Main loop has an ERROR, restarting 'target_km_walked'
Traceback (most recent call last):
  File "pokebot.py", line 99, in main
    api.main_loop()
  File "C:\Users\lennon68\pokeBot\PoGoBoWo\pgoapi\pgoapi.py", line 601, in main_loop
    self.heartbeat()
  File "C:\Users\lennon68\pokeBot\PoGoBoWo\pgoapi\pgoapi.py", line 271, in heartbeat
    self.log.info("\n\nList of Pokemon:\n" + get_inventory_data(res, self.pokemon_names) + "\nTotal Pokemon count: " + str(get_pokemon_num(res)) + "\nEgg Hatching status: " + get_incubators_stat(res) + "\n")
  File "C:\Users\lennon68\pokeBot\PoGoBoWo\pgoapi\poke_utils.py", line 56, in get_incubators_stat
    km_walked), inventory_items_incubator_list)))
  File "C:\Users\lennon68\pokeBot\PoGoBoWo\pgoapi\poke_utils.py", line 55, in <lambda>
    x['target_km_walked'],
KeyError: 'target_km_walked'
2016-08-03 00:21:06,812 [auth_google] [ INFO] Google login for:

It is hitting some pokestops (although it's saying it has less than 1 poke ball so I don't know how that's working...).  Config file attached.

[config_clean.txt](https://github.com/BoBeR182/PoGoBoWo/files/398703/config_clean.txt)

**Comment by BoBeR182** [comment]
Should have been fixed in f2737bbb8001e8e04a2bb3dc0856e43acc82ec5d, what commit are you on?
