### ISSUE TITLE
"web_port" error

### ISSUE THREAD

**Issue by nthwave** [BoBeR182/PoGoBoWo#67]
### Environmental Information

Operating System: Win 7 sp1 (with all updates)
Commit: latest
config.json:

## Steps to reproduce
Installed Python version 2.7
Installed python27C++
Installed pip
Downloaded PoGoBoWo-master.zip
Unzipped PoGoBoWo-master.zip to C:\temp
Change into the directory cd C:\temp\PoGoBoWo-master\
Install the dependencies with: pip install -r requirements.txt
Create a Google Maps Directions API key
Activated Google Maps Directions API key
Copied config.json.example config.json file.
Edit the config.json with:
	username,
	location,
	password,
	Google API,
If you login into Pokemon Go with Pokemon Trainer's Club: python pokebot.py -i 1
When running the bot for the first time add --cache to the end.

------------------ ERROR --------------------

PS C:\temp\PoGoBoWo-master> python pokebot.py -i 1 --cache
Traceback (most recent call last):
	File "pokebot.py", line 109, in <module>
		main()
	File "pokebot.py", line 93, in main
		thread.start_new_thread(start_server, (api, config.WEB_PORT))
AttributeError: 'Namespace' object has no attribute 'WEB_PORT'
PS C:\temp\PoGoBoWo-master

**Comment by BoBeR182** [comment]
Can you post your config.json with username pass and API redacted.

**Comment by VeNoMouS** [comment]
@BoBeR182 i hit that before, its missign a sanity check if there is no WEB_PORT defined in the config.

**Comment by BoBeR182** [comment]
Or users should be using the full config.json.example, I'm sure if we set a default it will crash if another app is binded to it already.

**Comment by nthwave** [comment]
Thanks for the assist everyone - noted that my config.json file did not have WEB_PORT in the PTC section - added it and its going now.
