### ISSUE TITLE
Starting RPC login sequence (app simulation)

### ISSUE THREAD

**Issue by onyshchenko** [BoBeR182/PoGoBoWo#69]
Operating System:
Linux UbuntuVital 3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Commit:
git status
On branch new-api-update
Your branch is up-to-date with 'origin/new-api-update'.

nothing to commit, working directory clean

$ python run_bot.py -i 1 -v -c
2016-08-11 06:50:56,105 [    pgoapi] [ INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-08-11 06:50:56,106 [    pgoapi] [DEBUG] Set Position - Lat: 50.4424323 Long: 30.5139853 Alt: 0.0
2016-08-11 06:50:56,106 [    pgoapi] [DEBUG] Auth provider: ptc
2016-08-11 06:50:56,106 [  auth_ptc] [ INFO] PTC User Login for: Tr3sd45
2016-08-11 06:50:56,114 [connectionpool] [ INFO] Starting new HTTPS connection (1): sso.pokemon.com
2016-08-11 06:50:56,524 [connectionpool] [DEBUG] "GET /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize HTTP/1.1" 200 104
2016-08-11 06:50:56,690 [connectionpool] [DEBUG] "POST /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize HTTP/1.1" 302 0
2016-08-11 06:50:56,838 [connectionpool] [DEBUG] "GET /sso/oauth2.0/callbackAuthorize?ticket=ST-12298070-kGih9Bn2OAdEmWefBy6M-sso.pokemon.com HTTP/1.1" 500 None
2016-08-11 06:50:56,839 [  auth_ptc] [ INFO] PTC User Login successful.
2016-08-11 06:50:56,839 [      auth] [DEBUG] No Access Token available!
2016-08-11 06:50:56,839 [  auth_ptc] [ INFO] Request PTC Access Token...
2016-08-11 06:50:56,996 [connectionpool] [DEBUG] "POST /sso/oauth2.0/accessToken HTTP/1.1" 200 106
2016-08-11 06:50:56,997 [  auth_ptc] [ INFO] PTC Access Token successfully retrieved.
2016-08-11 06:50:56,997 [  auth_ptc] [DEBUG] PTC Access Token: TGT-12245091-uqEzaBJlnhna...
2016-08-11 06:50:57,000 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-08-11 06:50:57,000 [    pgoapi] [DEBUG] Creating a new request...
2016-08-11 06:50:57,000 [    pgoapi] [DEBUG] Adding 'GET_PLAYER' to RPC request
2016-08-11 06:50:57,001 [    pgoapi] [DEBUG] Adding 'GET_HATCHED_EGGS' to RPC request
2016-08-11 06:50:57,001 [    pgoapi] [DEBUG] Adding 'GET_INVENTORY' to RPC request
2016-08-11 06:50:57,001 [    pgoapi] [DEBUG] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-08-11 06:50:57,001 [    pgoapi] [DEBUG] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-08-11 06:50:57,001 [    pgoapi] [DEBUG] Arguments of 'DOWNLOAD_SETTINGS':
{'hash': '54b359c97e46900f87211ef6e6dd0b7f2a3ea1f5'}
2016-08-11 06:50:57,001 [   rpc_api] [DEBUG] Generated new random RPC Request id: 310239505291550400
2016-08-11 06:50:57,001 [    pgoapi] [DEBUG] Execution of RPC
2016-08-11 06:50:57,002 [   rpc_api] [DEBUG] Generating main RPC request...
2016-08-11 06:50:57,002 [   rpc_api] [DEBUG] Incremented RPC Request ID: 310239505291550401
2016-08-11 06:50:57,002 [   rpc_api] [DEBUG] Generating sub RPC requests...
2016-08-11 06:50:57,015 [   rpc_api] [DEBUG] Subrequest class: POGOProtos.Networking.Requests.Messages_pb2.DownloadSettingsMessage
2016-08-11 06:50:57,015 [   rpc_api] [DEBUG] No Session Ticket found - using OAUTH Access Token
2016-08-11 06:50:57,015 [      auth] [DEBUG] Access Token still valid for further 02:58:00 hours (1470898377 < 1470909057)
2016-08-11 06:50:57,015 [  auth_ptc] [DEBUG] Using cached PTC Access Token
2016-08-11 06:50:57,016 [   rpc_api] [DEBUG] Generated protobuf request:
status_code: 2
request_id: 310239505291550401
requests {
  request_type: GET_PLAYER
}
requests {
  request_type: GET_HATCHED_EGGS
}
requests {
  request_type: GET_INVENTORY
}
requests {
  request_type: CHECK_AWARDED_BADGES
}
requests {
  request_type: DOWNLOAD_SETTINGS
  request_message: "\n(54b359c97e46900f87211ef6e6dd0b7f2a3ea1f5"
}
unknown6 {
  request_type: 6
  unknown2 {
    unknown1: "]\310SrE\357~\265\371\360\326_\342%\353\245\355ya\304\rs\2148\346\r\217\005\264)\004\020\271]\020\236\227Moy\257\3338\307\367\351\274g\255j\324\\\260\177-\025\243\\rbS(f\027\tC\013\366\2170\247\3237\353\031\276\312\273\333\305s\003P\255\344F\225\027\0079\254\220\362L\247\313\234\235\353\265\365B\344\333\327\223G\262\016\372\267wVG\235Xl}\204\202\253*\202\272\354\321+e\315{\227\366\236\233\336\354\255\356c\274\376Vlk\224\307W\336}\210n{\247\260\235\215\204\331\031@\271\354\205\216\203\244.\322\316\"|\306\225M(\254\004\270Z\277b\351\302[\237\340`\315\033/\263\365L\305\255>ff\333B\363Mo\323\255\226\3574\022\244%\232W\302\001\266U\304u\372n\312D@\344\267\302\256\202\177Z5\2108\'\350\347\337\314/i\246\037w\366\247d\005\264\357\351\343\327\201\203\321\267\250\334\356[I.\377\250\237\002\026\",\255\233\212\273H,\300\330^\266\270Y\350\252\202\322\232h"
  }
}
latitude: 50.4424323
longitude: 30.5139853
altitude: 8
auth_info {
  provider: "ptc"
  token {
    contents: "TGT-12245091-uqEzaBJlnhnaX2QBxT11b10FIdNj6cNnYCy0WrUrYLcUBrrDIU-sso.pokemon.com"
    unknown2: 59
  }
}
unknown12: 989

2016-08-11 06:50:57,017 [   rpc_api] [DEBUG] Execution of RPC
2016-08-11 06:50:57,019 [connectionpool] [ INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-08-11 06:50:57,516 [connectionpool] [DEBUG] "POST /plfe/rpc HTTP/1.1" 403 None
2016-08-11 06:50:57,517 [   rpc_api] [DEBUG] Parsing main RPC response...
Traceback (most recent call last):
  File "run_bot.py", line 132, in <module>
    main()
  File "run_bot.py", line 118, in main
    if not bot.login(config.auth_service, config.username, config.password, config.cached):
  File "/home/iz/PoGoBoWo_new-api-update/pogobot/pogobot.py", line 548, in login
    response = self.api.app_simulation_login()
  File "/home/iz/PoGoBoWo_new-api-update/pgoapi/pgoapi.py", line 151, in app_simulation_login
    response = request.call()
  File "/home/iz/PoGoBoWo_new-api-update/pgoapi/pgoapi.py", line 233, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/iz/PoGoBoWo_new-api-update/pgoapi/rpc_api.py", line 128, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/iz/PoGoBoWo_new-api-update/pgoapi/rpc_api.py", line 332, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...

[config_json.txt](https://github.com/BoBeR182/PoGoBoWo/files/412668/config_json.txt)

**Comment by etrevis** [comment]
`Seems your IP Address is banned or something else went badly wrong`
Try changing IP address (restart your modem or use your smartphone hotspot)

**Comment by BoBeR182** [comment]
Did you login with the wrong password too many times?

**Comment by onyshchenko** [comment]
No password is written correctly.

Change the IP address is not so easy, because all running on the server in the Microsoft Cloud.
I start the virtual machine with Ubuntu Server, but now another error:
vitaliy@ubuntu:~/PoGoBoWo_new-api-update$ python run_bot.py -h
Traceback (most recent call last):
  File "run_bot.py", line 132, in <module>
    main()
  File "run_bot.py", line 80, in main
    config = init_config()
  File "run_bot.py", line 54, in init_config
    required=required("auth_service"))
  File "run_bot.py", line 51, in required
    return x not in load['accounts'][0].keys()
KeyError: 'accounts'
vitaliy@ubuntu:~/PoGoBoWo_new-api-update$ git pull
Already up-to-date.

This error occurs because of what?

**Comment by onyshchenko** [comment]
Problem solved.

Changing IP addresses helped.

Whatever occurred **KeyError: 'accounts'** need to add a check for the presence of the file:
```
    if not os.path.isfile(config_file):
        log.error("I can not find the file config.json")
        return None
```
Thank you all for the help.
