### ISSUE TITLE
Bot has been working fine, checked it this morning and when I try to run it im getting this error

### ISSUE THREAD

**Issue by littleoz2** [BoBeR182/PoGoBoWo#78]
2016-08-15 09:14:02,048 [    pgoapi] [ INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-08-15 09:14:02,049 [  auth_ptc] [ INFO] PTC User Login for: PoGoMaster123456
2016-08-15 09:14:02,658 [  auth_ptc] [ INFO] PTC User Login successful.
2016-08-15 09:14:02,658 [  auth_ptc] [ INFO] Request PTC Access Token...
2016-08-15 09:14:02,811 [  auth_ptc] [ INFO] PTC Access Token successfully retrieved.
2016-08-15 09:14:02,826 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-08-15 09:14:03,570 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
Traceback (most recent call last):
  File "run_bot.py", line 132, in <module>
    main()
  File "run_bot.py", line 118, in main
    if not bot.login(config.auth_service, config.username, config.password, config.cached):
  File "/home/pogo/PoGoBoWo/pogobot/pogobot.py", line 551, in login
    self.response_parser(res=response)
  File "/home/pogo/PoGoBoWo/pogobot/pogobot.py", line 187, in response_parser
    inventory_items = json_file.get('GET_INVENTORY', {}).get('inventory_delta', {}).get('inventory_items', [])
UnboundLocalError: local variable 'json_file' referenced before assignment

**Comment by BoBeR182** [comment]
You might have gotten banned, check via phone app

**Comment by littleoz2** [comment]
when I try to log in on the phone app it won't let me and says something about a server problem, but I checked on the server status page and all the servers seem to be up, so seems like it might be banned, would this be a permanent ban?

**Comment by BoBeR182** [comment]
No one knows yet, did you get an email stating you have violated ToS.

You can stop botting for a bit and see if it fixes it self.

follow pokemongobotting.reddit.com to see more info about bans

**Comment by littleoz2** [comment]
No didn't get an email or anything, okay then thank you
