### ISSUE TITLE
[ERROR] Main loop has an ERROR, restarting REQUEST_DENIED This API project is not authorized to use this API.

### ISSUE THREAD

**Issue by Panhouba** [BoBeR182/PoGoBoWo#79]
Hello,

can you help me with this error?

2016-08-17 00:40:08,973 [   pogobot] [ INFO] Walking to fort at 50.100914,14.417
293
2016-08-17 00:40:09,315 [   run_bot] [ERROR] Main loop has an ERROR, restarting
REQUEST_DENIED (This API project is not authorized to use this API. Please ensur
e this API is activated in the Google Developers Console: https://console.develo
pers.google.com/apis/api/elevation_backend?project=_)
Traceback (most recent call last):
  File "run_bot.py", line 122, in main
    bot.main_loop()
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 645,
 in main_loop
    self.heartbeat()
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 217,
 in heartbeat
    self.spin_near_fort()
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 279,
 in spin_near_fort
    self.walk_to((fort['latitude'], fort['longitude']))
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 226,
 in walk_to
    final_point = append_elevation(next_point[1][0], next_point[1][1], self.GMAP
S_KEY)
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\location.py", line 49,
 in append_elevation
    response = request_google.elevation(locations=location)
  File "C:\Python27\lib\site-packages\googlemaps\elevation.py", line 37, in elev
ation
    return client._get("/maps/api/elevation/json", params)["results"]
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 240, in _get
    result = self._get_body(resp)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 263, in _get_b
ody
    body["error_message"])
ApiError: REQUEST_DENIED (This API project is not authorized to use this API. Pl
ease ensure this API is activated in the Google Developers Console: https://cons
ole.developers.google.com/apis/api/elevation_backend?project=_)

Thank you!

**Comment by jefftham** [comment]
Actually this bot requires two google api to run.    
Google Maps Elevation API and  Google Maps Directions API .   
In your case, i believe your Google Maps Elevation API  is not running.    
steps to enable it:-    
1) go to https://console.developers.google.com/   
2) select project   
3)  click "Library" on the left side (api manager section)   
2) Google Maps APIs > more > Google Maps Elevation API    
3) click "Enable"

**Comment by Panhouba** [comment]
Problem solved!

Thank you, man :+1:
