### ISSUE TITLE
[ERROR] Main loop has an ERROR, restarting  Traceback

### ISSUE THREAD

**Issue by Panhouba** [BoBeR182/PoGoBoWo#81]
Hi, can someone help me with this timeout error?

2016-08-18 00:30:52,157 [   run_bot] [ERROR] Main loop has an ERROR, restarting

Traceback (most recent call last):
  File "run_bot.py", line 122, in main
    bot.main_loop()
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 645,
 in main_loop
    self.heartbeat()
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 217,
 in heartbeat
    self.spin_near_fort()
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 279,
 in spin_near_fort
    self.walk_to((fort['latitude'], fort['longitude']))
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\pogobot.py", line 226,
 in walk_to
    final_point = append_elevation(next_point[1][0], next_point[1][1], self.GMAP
S_KEY)
  File "C:\Users\Petrasek\Desktop\PoGoBoWo-master\pogobot\location.py", line 49,
 in append_elevation
    response = request_google.elevation(locations=location)
  File "C:\Python27\lib\site-packages\googlemaps\elevation.py", line 37, in elev
ation
    return client._get("/maps/api/elevation/json", params)["results"]
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 246, in _get
    base_url, accepts_clientid, extract_body)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 201, in _get
    raise googlemaps.exceptions.Timeout()
Timeout

Update: I have this problem only on one computer. Bot on another computer running fine.
Thank you!

Panhouba

**Comment by BoBeR182** [comment]
Copy over the configuration from your other computer, and see what changes you may have missed.

A timeout error is network related, do you have a bad connection or unstable internet?

**Comment by fred410** [comment]
Hello, i started getting this yesterday and now getting it today.
Its not a network timeout thing. When I call the test URL directly (described below) - it tells me:
   "error_message" : "You have exceeded your daily request quota for this API.",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"

If you want to see what your issue is use the google's own API test URL (with your API key pasted in) into a web browser and see what messages you get back.

URL is:
https://maps.googleapis.com/maps/api/elevation/json?locations=39.7391536,-104.9847034&key=YOUR_API_KEY

**Comment by BoBeR182** [comment]
Google limited your API key you only get so many a day.
