### ISSUE TITLE
bad file descriptor error

### ISSUE THREAD

**Issue by johnscancella** [BoBeR182/PoGoBoWo#84]
I keep seeing
```
2016-09-13 19:46:47,919 [   pogobot] [ INFO] Catching Pokemon: Oddish
Exception in thread Thread-614:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.handle_error(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor
```

## Expected Behavior
run without error

## Actual Behavior
erros show in the log

### Environmental Information
Python 2.7.10

Operating System: mac OS X
Commit: 0667fcd49ea340252ba4a1cf37b954470a4aa545

1. run `python run_bot.py -i 0`
2. see error in log

**Comment by BoBeR182** [comment]
This looks like a bug in python on Mac nothing with our code as you can see the lines are all relating to the socket.py file.

**Comment by johnscancella** [comment]
I figured as much, just was wondering if you had any advice on where in your code it is spawning this. That way I can more easily create a test and report the bug upstream.
